"""add_children_ages_to_rsvp_responses

Revision ID: 41bc5cd8c27c
Revises: 6a1b6a26d1e9
Create Date: 2026-07-07 22:33:47.411282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41bc5cd8c27c'
down_revision = '6a1b6a26d1e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rsvp_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('children_ages', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rsvp_responses', schema=None) as batch_op:
        batch_op.drop_column('children_ages')

    # ### end Alembic commands ###
