"""initial

Revision ID: 483d712fd35b
Revises: 
Create Date: 2026-07-07 20:49:41.622899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '483d712fd35b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guestbook_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_name', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rsvp_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edit_token', sa.String(length=36), nullable=False),
    sa.Column('email_contact', sa.String(length=254), nullable=True),
    sa.Column('song_suggestion', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('need_accommodation', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('edit_token')
    )
    op.create_table('rsvp_guests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('guest_type', sa.String(length=20), nullable=False),
    sa.Column('attending', sa.Boolean(), nullable=False),
    sa.Column('menu_choice', sa.String(length=255), nullable=True),
    sa.Column('allergies', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['rsvp_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rsvp_guests')
    op.drop_table('rsvp_groups')
    op.drop_table('guestbook_entries')
    # ### end Alembic commands ###
