"""invitees_and_rsvp_responses

Revision ID: 6a1b6a26d1e9
Revises: 483d712fd35b
Create Date: 2026-07-07 21:42:59.935220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a1b6a26d1e9'
down_revision = '483d712fd35b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('has_partner', sa.Boolean(), nullable=False),
    sa.Column('partner_first_name', sa.String(length=100), nullable=True),
    sa.Column('partner_last_name', sa.String(length=100), nullable=True),
    sa.Column('max_children', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('rsvp_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invitee_id', sa.Integer(), nullable=False),
    sa.Column('edit_token', sa.String(length=36), nullable=False),
    sa.Column('principal_attending', sa.Boolean(), nullable=False),
    sa.Column('principal_menu', sa.String(length=255), nullable=True),
    sa.Column('principal_allergies', sa.String(length=500), nullable=True),
    sa.Column('partner_attending', sa.Boolean(), nullable=True),
    sa.Column('partner_menu', sa.String(length=255), nullable=True),
    sa.Column('partner_allergies', sa.String(length=500), nullable=True),
    sa.Column('children_attending_count', sa.Integer(), nullable=False),
    sa.Column('children_menu', sa.String(length=255), nullable=True),
    sa.Column('children_allergies', sa.String(length=500), nullable=True),
    sa.Column('email_contact', sa.String(length=254), nullable=True),
    sa.Column('song_suggestion', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('need_accommodation', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invitee_id'], ['invitees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('edit_token'),
    sa.UniqueConstraint('invitee_id')
    )
    op.drop_table('rsvp_guests')
    op.drop_table('rsvp_groups')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rsvp_groups',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('edit_token', sa.VARCHAR(length=36), nullable=False),
    sa.Column('email_contact', sa.VARCHAR(length=254), nullable=True),
    sa.Column('song_suggestion', sa.VARCHAR(length=255), nullable=True),
    sa.Column('message', sa.TEXT(), nullable=True),
    sa.Column('need_accommodation', sa.BOOLEAN(), nullable=False),
    sa.Column('submitted_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('edit_token')
    )
    op.create_table('rsvp_guests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('guest_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('attending', sa.BOOLEAN(), nullable=False),
    sa.Column('menu_choice', sa.VARCHAR(length=255), nullable=True),
    sa.Column('allergies', sa.VARCHAR(length=500), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['rsvp_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('rsvp_responses')
    op.drop_table('invitees')
    # ### end Alembic commands ###
