"""replace_menu_allergies_with_entree_plat

Revision ID: e8de92f76798
Revises: 41bc5cd8c27c
Create Date: 2026-07-07 22:49:53.818578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8de92f76798'
down_revision = '41bc5cd8c27c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rsvp_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('principal_entree', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('principal_plat', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('partner_entree', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('partner_plat', sa.String(length=255), nullable=True))
        batch_op.drop_column('partner_menu')
        batch_op.drop_column('children_allergies')
        batch_op.drop_column('principal_menu')
        batch_op.drop_column('principal_allergies')
        batch_op.drop_column('partner_allergies')
        batch_op.drop_column('children_menu')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rsvp_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('children_menu', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('partner_allergies', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('principal_allergies', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('principal_menu', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('children_allergies', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('partner_menu', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('partner_plat')
        batch_op.drop_column('partner_entree')
        batch_op.drop_column('principal_plat')
        batch_op.drop_column('principal_entree')

    # ### end Alembic commands ###
